storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

pytorch_version:
  value: "1.4.0"
  wizard:
    name: "PyTorch version"
    kind: select
    options:
    - "1.3.1"
    - "1.4.0"

useGPU:
  value: false
  wizard:
    name: Enable GPU in Jupyter
    kind: boolean

chapters:
  value: https://github.com/kuberlab-catalog/pytorch-computer-vision-cookbook/tree/master/chapters
  wizard:
    name: "Chapters"
    kind: git

dataset:
 value: 'histopathological-cancer-detection'
 version: '1.0.1'
 workspace: 'kuberlab-demo'
 wizard:
   name: "Cancer detection dataset"
   kind: dataset

# Pip packages may be specified here in format that pip accepts.
# Install for two iterations because pycocotools can not be installed w/o installed Cython
packages:
  - albumentations==0.4.2
  - cycler==0.10.0
  - imgaug==0.2.6
  - opencv-python-headless==4.1.1.26
  - Cython==0.29.16
  - torchsummary==1.5.1
packages2:
  - pycocotools==2.0
